stages:
  split:
    cmd: python src/split.py
    deps:
    - resources/train.csv
    - src/split.py
    params:
    - split
    outs:
    - resources/test_data.csv
    - resources/train_data.csv
  train:
    cmd: python src/train.py
    deps:
    - resources/train_data.csv
    - src/train.py
    params:
    - train
    outs:
    - resources/model.pkl
