name: test

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: iterative/setup-cml@v1

      - uses: iterative/setup-dvc@v1

      - uses: actions/setup-python@v2

        with:
          python-version: '3.x'

      - name: Train model
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          # Install requirements
          pip install -r requirements.txt
          pip install -r requirements_dvc.txt
          
          # Pull dataset with DVC 
          dvc pull
          echo "## Metrics (comparing with the master branch)" >> report.md          
          git fetch --prune
          dvc metrics diff main --show-md >> report.md
          echo "## Visualizations" >> report.md   
          cml send-comment report.md